---
title: "Association Test Anaysis"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(car)
```

First, we read in the resutls from the -doAsso 1 (run in ANGSD) test. We will start with the El Cope West dataset.

```{r}
#read in data and assign column names
asso_data <- read.table("Asso1_out_tig_trim1.lrt0")
colnames(asso_data) <- c(as.character(asso_data[1,1]),as.character(asso_data[1,2]), as.character(asso_data[1,3]), as.character(asso_data[1,4]), as.character(asso_data[1,5]), as.character(asso_data[1,6]))

#El Cope West has 611670 SNPs

#convert data and sort table
asso_data <- asso_data[-1,]
asso_data$LRT <- as.numeric(as.character(asso_data$LRT))
test1 <- order(asso_data$LRT, decreasing = FALSE)
asso_data_sort <- asso_data[test1,]


#generate p values based on a chi square distribution with df=1
asso_data_p <- pchisq(asso_data_sort$LRT, df=1, lower.tail=FALSE)

#make one table to write out
asso_data_all <- cbind(asso_data_sort, pchisq(asso_data_sort$LRT, df=1, lower.tail=FALSE))
write.csv(asso_data_all, file="Asso1_tig_trim_with_pvalues.csv")

#generate null distribution
y <- rchisq(nrow(asso_data), df = 1)

expected_p <- pchisq(y, df=1, lower.tail=FALSE)

asso_data_lrt <- asso_data_sort$LRT


#plot using qqplot function

qqplot(y,asso_data_lrt, 
       main = expression("Q-Q plot for" ~~ {chi^2}[nu == 1]))
qqline(y, distribution = function(p) qchisq(p, df = 1),
       probs = c(0.25, 0.75), col = 2)

#plot a different way using qqPlot function from the car package
#this is the plot used in the paper

qqPlot(asso_data_lrt, dist='chisq', df=1, line="robust")


```

Now we do the same for the A. varius dataset.


```{r}
#read in data and assign column names
asso_data_v <- read.table("Asso1_out_varius_trim_fix.lrt0")
colnames(asso_data_v) <- c(as.character(asso_data_v[1,1]),as.character(asso_data_v[1,2]), as.character(asso_data_v[1,3]), as.character(asso_data_v[1,4]), as.character(asso_data_v[1,5]), as.character(asso_data_v[1,6]))

#varius has 1040758 SNPs

asso_data_v <- asso_data_v[-1,]
asso_data_v$LRT <- as.numeric(as.character(asso_data_v$LRT))
test1 <- order(asso_data_v$LRT, decreasing = FALSE)
asso_data_v_sort <- asso_data_v[test1,]

asso_data_v_p <- pchisq(asso_data_v_sort$LRT, df=1, lower.tail=FALSE)

y <- rchisq(nrow(asso_data_v), df = 1)
expected_p <- pchisq(y, df=1, lower.tail=FALSE)

asso_data_v_lrt <- asso_data_v_sort$LRT


#make a chi square dist with 4 degrees of freedom
y <- rchisq(nrow(asso_data_v), df = 1)


#method one for plotting 
qqplot(y,asso_data_v_lrt, 
       main = expression("Q-Q plot for" ~~ {chi^2}[nu == 1]))
qqline(y, distribution = function(p) qchisq(p, df = 1),
       probs = c(0.25, 0.75), col = 2)

#method two for plotting
#this is the plot used in the paper
qqPlot(asso_data_v_lrt, dist='chisq', df=1, line="robust")


```





